Fix: Correct asset path in s_daterange.xml for online_appointment module
- Fix asset path from 's2u_online_appointment/static/src/snippets/s_daterange/000.xml'
  to 'online_appointment/static/src/snippets/s_daterange/000.xml'
- The s2u_online_appointment module doesn't exist, causing "uninstalled module" error
- The actual static file is located in online_appointment module
- This resolves RPC Error #6: AssertionError - snippet_daterange.s_daterange_000_xml refers to uninstalled module

Error resolved:
AssertionError: The ID "snippet_daterange.s_daterange_000_xml" refers to an uninstalled module